IBM/taxinomitis

public/components/login/login.css, public/components/login/login.html
This commit adds the Auth0 badge to all UI pages relating to creating
accounts or logging in. This is a requirement for the Auth0 OSS program.
Closes: #28
=> feat: Auth0 OSS badge

public/app.js, public/components/mlproject/mlproject.html, public/components/python/python.controller.js, public/components/python/python.css, public/components/python/python.html, src/lib/restapi/scratch.ts
This is the start of a new page that demonstrates how to drive the
Scratch Keys API from Python code.
The idea is to make this an alternative option for older students who
might find Scratch too simplistic or limiting.
This PR enables Python projects for text and images projects only.
I'm using Angular binding to allow students to customize the data that
the Python code should submit to the classifier, with the sample code
updating live.
Sample code for images comes in two flavours - classifying a local
image file or classifying an image from the Internet.
I haven't done numbers projects because I haven't found a way to cover
multi-choice and numeric values in a way that is simple and easy to
follow.
I also need at least one worksheet to show how this could be used
before this issue can …
=> feat: Support for Python projects

src/lib/imagestore/bulkdelete.ts, src/lib/imagestore/index.ts, src/lib/imagestore/keys.ts
This commit will throw an uncaught exception at startup if we can't
query the object store bucket for keys.
Closes: #19
=> chore: Verify Object Store bucket exists at startup

src/lib/restapi/users.ts
A free tier VR API key now allows two machine learning models, where it
used to allow 1. This commit updates the sum that is used to display
the number of allowed models to match this new allowance.
Contributes to: #20
=> chore: Update allowance for free VR API keys

.gitignore, gulpfile.js, public/app.js, public/components/mlproject/mlproject.html, public/components/python/python.html, public/components/scratch3/scratch3.controller.js, public/components/scratch3/scratch3.html, public/index.html, public/languages/en.json, resources/scratch3-text-classify.js, src/lib/restapi/config.ts, src/lib/restapi/scratch.ts, src/lib/restapi/urls.ts, src/lib/scratchx/extensions.ts, src/tests/scratchx/extensions.ts
Initial implementation of a Scratch 3 extension. Only the text extension
is implemented so far, as it's the simplest of the three.
It's functional enough to be used, so it's shown in the UI - although
clearly marked as an early alpha.
Almost all of the functionality from the Scratch 2 version (e.g. caching,
throttling, support for getting labels and confidence scores, ability to
add training data, etc.) is present.
The only thing missing is the status indicator, which doesn't seem to be
included in the Scratch 3 UI. It means there's no clear way to show
whether the machine learning model is ready / functional.
Contributes to: #21
=> feat: Scratch 3 support

public/app.js, public/app.run.js, public/bower.json, public/components/auth/auth.service.js
When users click the Verify Email Address link they get in an email, it
will go first to auth0.com, and then redirect to
machinelearningforkids.co.uk with a query parameter confirming the
outcome.
This commit looks for that query parameter and displays a dialog if
found to let the user know that it worked.
It uses `window.location` to send the user to the home page while clearing
the query parameter to prevent it being displayed again.
Closes: #9
=> feat: Display confirmation when verifying email addresses

public/components/training/ignoreDrop.directive.js, public/components/training/training.html
This adds a new directive that swallows drag-and-drop events to prevent
browser navigation from accidental drops outside of a training bucket.
Closes: #87
=> fix: Handle accidental drops outside of training buckets

public/components/mlcanvas/mlcanvas.css
Flex seems to have different defaults on Internet Explorer than on
any other browser. Because of course it does.
Added some IE-specific CSS to get IE to mirror the behaviour of
the other browsers.
Closes: #112
=> fix: CSS fix for canvas on Internet Explorer

public/components/training/training.css
For mobile, make the buckets a bit easier to read. Because scrolling is easy on mobile, just render all of the buckets at their full height. 
If you'd rather a max height on each bucket, just set the height/max-height property in the css. If going for a max height, I'd recommend `100vh`
=> feat: Improve buckets on mobile

src/lib/training/conversation.ts
There is a new IBM Cloud region hosting Watson Assistant now, so
I need to add the URL for it to the site. This will enable
credentials created in that region to be used.
Closes: #133
=> fix: Add support for Watson Assistant instances in Tokyo

public/index.html
When #164 is merged (German) then this adds the german language option in the dropdown menu in the header.
This also adds emojis for each language - because we're super modern yo
=> feat: Include DE in drop down, plus emojis!

public/index.html
The emojis in the language drop down are not rendering correctly on some Windows devices. I think it's because we're not setting the HTML to UTF-8 as per [these instructions](https://www.kirupa.com/html5/emoji.htm)
=> feat: Add UTF-8 support in the HTML

sql/tables.sql
Indexing the whole imageurl column in the imagetraining table was
causing problems for two developers. My best guess is that the
character set they have as a default has wider characters than
what I'm using, resulting in the index exceeding MySQL default
limits.
In hindsight, indexing the whole column is excessive. Looking at
the data in the current production site, 90% of the rows have a
imageurl that is 250 characters or fewer, so I think a prefix
index will be sufficient. (Not only will it hopefully resolve
the error reported, I think it should be more efficient).
Contributes to: #225
=> fix: Switch URL index to a prefix index

serverless-functions/mltraining-numbers/numbers.py
The library I'm using to build decision tree classifiers has a random
element to how it performs splits during training. This means two
students using the same training data might see different results.
Or a student who retrains their model without making changes to their
training data might see different results.
In the interest of avoiding potential confusion this might cause,
this commit introduces a fixed seed to make it more deterministic.
I've picked a seed of 42 because it is the ultimate answer. :-)
Closes: #229
=> feat: Make numbers ML models more deterministic

public/components/appinventor/appinventor.controller.js, public/components/appinventor/appinventor.html, public/components/scratch3/scratch3.html, public/languages/cs.json, public/languages/de.json, public/languages/el.json, public/languages/en.json, public/languages/es.json, public/languages/fr.json, public/languages/it.json, public/languages/ja.json, public/languages/ko.json, public/languages/nl-be.json, public/languages/pt-br.json, public/languages/si-lk.json, public/languages/sv-se.json, public/languages/tr.json, public/languages/zh-cn.json
Now that the App Inventor extension has additional blocks
for collecting training data and training models, there
is no need to restrict the App Inventor extension to
projects with a trained model.
This commit reworks the App Inventor launch page to
provide options for projects still in progress.
Closes: #247
=> feat: Use App Inventor to train ML models

src/lib/utils/downloadAndZip.ts
The most common reason for failing to create training zip files in OpenWhisk
is that the serverless function CreateZip creates a zip file that is larger
than the 5mb response payload limit that IBM Cloud Functions allows.
This needs some significant redesign/restructuring to handle it, but for now,
we'll just workaround the problem by handling these (fortunately rare) edge
cases by building the zip outside of OpenWhisk.
This is only done for unexpected failures - if the OpenWhisk function returns
an error payload, we just use the error description in it.
Contributes to: #263
=> fix: Create very large training zips locally

src/lib/restapi/watsonapis.ts, src/lib/training/conversation.ts, src/lib/training/visualrecognition.ts, src/tests/restapi/watsonapis.ts
Watson service instances can now be created in the Seoul region.
This commit adds support for the Seoul API endpoints.
Closes: #272
=> feat: Support for Watson API keys provisioned in Seoul

public/components/models/models.controller.js, public/components/models/models.html, public/components/soundtraining/soundtraining.service.js, public/components/training/training.controller.js, resources/scratch3-sound-classify.js
Models for sound projects saved in the browser are now
stored in IndexedDB so that they don't need to be trained
from scratch after every page load.
This makes the behaviour more consistent with projects
that use cloud-hosted models (text/images/numbers) so will
help students who are used to training their model from
the training tool page, and then making predictions from
Scratch projects.
Contributes to: #356
=> feat: Support for saving TensorFlowJS models in indexeddb

Dockerfile, docker-compose.yml
I had a go at a docker-compose setup to build and run a containerised version of ML4Kids:
- postgres container
- node container that builds ML4Kids.
Possible next steps:
- clean the ML4Kids container of build artefacts;
- try a docker `buildx` crossbuild Github Action to try to build versions for RPi ([crib example](https://github.com/OpenComputingLab/vce-jupyter-stacks/blob/main/.github/workflows/buildx-base.yml))
=> Docker-compose setup for ML4Kids

src/lib/sessionusers/index.ts
This is needed to remove training data for image and sound
projects.
It was already done for regular users when user accounts are
deleted, but not session users.
=> fix: Cleanup cloud object storage when session users are deleted
