gulpfile.js, public/app.js, public/bower.json, public/components/login/login.html, public/components/welcome/welcome.html, public/index.html, public/languages/en.json
Feature: Part of the application is now using translation strings.
Contributes to #23 
Implemented using [angular-translate](https://angular-translate.github.io/)
Strings are to be stored in `/src/languages/{lang-code}.json`
Language is determined by the browser, or overriden with URL query string `?lang={code}`, but falls back to english if that language file isn't found
Welcome page is now translated, and so is part of the login page.
=> feat: Initial batch of translations

public/languages/en.json
`children,and`  >> `children, and`
=> Minor fix on string #35

public/components/help/help.html, public/languages/en.json
=> chore: NLS updates

public/components/mlproject/mlproject.html, public/components/python/python.controller.js, public/components/python/python.html
This commit adds the template Python project for numbers projects.
Closes: #11
=> feat: Python support for numbers projects

public/components/mlproject/mlproject.html, public/components/python/python.html, public/components/scratch3/scratch3.controller.js, public/components/scratch3/scratch3.html, public/languages/en.json, resources/scratch3-numbers-classify.js, src/lib/scratchx/extensions.ts
This adds a new Scratch 3 extension for numbers projects. Now that
I've figured out how to get menus working, I've gone back and updated
the text extension to use menus where possible.
Contributes to: #21
=> feat: Numbers projects in Scratch 3

public/components/help/help.html, public/components/mlproject/mlproject.css, public/components/teacher/teacher.controller.js, public/components/teacher/teacher.css, public/components/teacher/teacher.html, public/components/users/users.service.js, public/languages/en.json, resources/email-deleted-class.html, resources/email-deleted-class.txt, src/lib/auth0/requests.ts, src/lib/auth0/users.ts, src/lib/classdeleter/index.ts, src/lib/notifications/email.ts, src/lib/restapi/users.ts
=> feat: REST API for deleting classes

public/components/quiz/quiz.service.js
Added one question on the difference between supervised and unsupervised learning, and one on machine learning in search engines.
=> Added two additional questions

public/components/mlproject/mlproject.html, public/components/scratch3/scratch3.controller.js, public/components/scratch3/scratch3.html, resources/scratch3-images-classify.js, resources/scratch3-numbers-classify.js, src/lib/scratchx/extensions.ts
=> feat: Images support in Scratch 3

src/lib/db/store.ts, src/lib/restapi/watsonapis.ts, src/lib/training/credentials.ts, src/tests/db/bluemixstore.ts
=> fix: Remove references to Bluemix credentials when they're deleted

public/components/models/models.html, public/languages/en.json, public/languages/ko.json, public/languages/pt-br.json, public/languages/sv-se.json
=> chore: NLS updates for Models page

public/components/projects/projects.css, public/components/teacher_supervision/teacher_supervision.css
=> fix: Fix image location for group icons in CSS

public/bower.json
=> chore: Update bower dependencies

package-lock.json, package.json, src/tests/restapi/appinventor.ts, src/tests/utils/downloadAndZip.ts, src/tests/utils/openwhisk.ts
=> chore: Replace unzip2 with unzipper

src/lib/db/store.ts
=> chore: Convert Bluemix API responses to charset used in MySQL

package-lock.json, package.json, public/components/soundtraining/soundtraining.service.js, src/lib/restapi/headers.ts, src/lib/restapi/scratch.ts
=> fix: Retrieve spectograms for training sound models

public/components/links/links.html
=> feat: Add new video to Links page

public/components/quiz/quiz.service.js, public/languages/cs.json, public/languages/de.json, public/languages/el.json, public/languages/en.json, public/languages/es.json, public/languages/fr.json, public/languages/it.json, public/languages/ja.json, public/languages/ko.json, public/languages/nl-be.json, public/languages/pt-br.json, public/languages/si-lk.json, public/languages/sv-se.json, public/languages/tr.json, public/languages/zh-cn.json
This commit removes the hard-coded quiz questions/answers from
the quiz service, and fetches them through the translations
service instead.
Closes: #253
=> feat: Enable NLS for quiz questions

public/components/soundtraining/soundtraining.service.js
=> fix: Protect against failure to load TensorFlow

public/languages/it.json
This is a complete Italian translation made entirely "by hand". Probably there's still something to fix :-)  
I hope you'll enjoy it.
=> Italian Translation

src/lib/training/visualrecognition.ts
=> chore: Improve error message for Vis Rec training failures

public/components/projects/projects.controller.js, public/components/projects/projects.css, public/components/projects/projects.html, public/components/projects/projects.service.js, public/languages/ar.json, public/languages/cs.json, public/languages/de.json, public/languages/el.json, public/languages/en.json, public/languages/es.json, public/languages/fr.json, public/languages/hr.json, public/languages/it.json, public/languages/ja.json, public/languages/ko.json, public/languages/nl-be.json, public/languages/pl.json, public/languages/pt-br.json, public/languages/ru.json, public/languages/si-lk.json, public/languages/sv-se.json, public/languages/tr.json, public/languages/zh-cn.json, public/languages/zh-tw.json, src/lib/db/store.ts, src/lib/restapi/projects.ts, src/lib/restapi/urls.ts, src/tests/restapi/projects.ts, src/tests/restapi/projectscrowdsourced.ts
=> feat: REST API for sharing projects

public/languages/de.json
More on the German translation. Still not complete, though :)
=> Improved German translation

public/languages/es.json
* Minor proposal on line 17
* syntax issue on line 131
*  minor fix on line 155
* syntax issue on line 156
* minor proposal on line 180
* duplicated word on line 205
=> Fixed typos on line 159 & 1469

public/languages/es.json
Add links to new translated worksheets submitted in
https://github.com/IBM/taxinomitis-docs/pull/19/
=> docs: Add new Spanish worksheets

public/languages/fr.json
I translated 250 lines.
thaks for your great job Dale !
Regards
=> update french translation complete

public/languages/fr.json
and I transladed Laser Eyes activity too !
=> some mistakes fixed ;-)

public/app.js, public/components/python/python.controller.js, public/components/python/python.css, public/components/python/python.html, public/components/pythonlocal/python.controller.js, public/components/pythonlocal/python.html, public/languages/ar.json, public/languages/cs.json, public/languages/de.json, public/languages/el.json, public/languages/en.json, public/languages/es.json, public/languages/fr.json, public/languages/hr.json, public/languages/it.json, public/languages/ja.json, public/languages/ko.json, public/languages/nl-be.json, public/languages/pl.json, public/languages/pt-br.json, public/languages/ru.json, public/languages/si-lk.json, public/languages/sv-se.json, public/languages/tr.json, public/languages/zh-cn.json, public/languages/zh-tw.json
=> feat: repl.it integration for Python projects

src/lib/db/store.ts, src/tests/db/projectstore.ts
=> fix: Deleting students should not deleted shared projects

gulpfile.js, public/components/appinventor/appinventor.controller.js, public/components/datasets/datasets.controller.js, public/components/describemodel/describemodel.controller.js, public/components/login/login.controller.js, public/components/makes/makes.controller.js, public/components/mlproject/mlproject.controller.js, public/components/models/models.controller.js, public/components/projects/projects.controller.js, public/components/python/python.controller.js, public/components/scratch3/scratch3.controller.js, public/components/signup/signup.controller.js, public/components/sitealerts/sitealerts.service.js, public/components/soundtraining/soundtraining.service.js, public/components/teacher_apikeys/teacher_apikeys.controller.js, public/components/teacher_students/teacher_students.controller.js, public/components/training/training.controller.js
=> chore: Add additional UI logging

src/lib/utils/bagofwords.ts, src/tests/training/describetext.ts, src/tests/utils/bagofwords.ts
=> tests: Unit test for NN describe function

src/tests/restapi/watsonapis.ts, src/tests/training/credentialscheck.ts
=> tests: Test for Watson credentials checking

ops/tenant.sh, src/lib/db/objects.ts, src/lib/db/store.ts, src/tests/db/objects.ts, src/tests/db/tenantstore.ts, src/tests/restapi/tenants.ts, src/tests/restapi/users.ts
=> chore: Remove images project type from new classes

public/languages/ro.json
I translated the worksheets page
=> Update ro.json 17042021

mlforkids-api/public/languages/cs.json
translated CZ version:
changes only in mlforkids-api/public/languages/cs.json
on request of Eva Necasova ([eva@designity.cz](mailto:eva@designity.cz)) from https://aidetem.cz/
=> Improve CZ translation

mlforkids-api/public/languages/ru.json
=> Some Russian Translation 
